version: '3.8'

services:
  techn_bt_tg_bot:
    image: node:18-alpine
    container_name: techn_bt_tg_bot
    restart: unless-stopped
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm install && npm start"